package Administrador;

/**
 *
 * @author gomez
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LogoSIC = new javax.swing.JLabel();
        TextLogo = new javax.swing.JLabel();
        LabelTexto = new javax.swing.JLabel();
        LabelTexto2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(234, 234, 234));
        setPreferredSize(new java.awt.Dimension(730, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(234, 234, 234));

        LogoSIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoSIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/Logo.png"))); // NOI18N

        TextLogo.setFont(new java.awt.Font("Roboto", 1, 34)); // NOI18N
        TextLogo.setForeground(new java.awt.Color(51, 51, 51));
        TextLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextLogo.setText("S I C");

        LabelTexto.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        LabelTexto.setForeground(new java.awt.Color(0, 0, 0));
        LabelTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTexto.setText("BIEVENIDO USUARIO AL MENÚ ");

        LabelTexto2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        LabelTexto2.setForeground(new java.awt.Color(0, 0, 0));
        LabelTexto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTexto2.setText("A LA IZQUIERDA ENCONTRARÁ LAS OPCIONES A LAS CUALES PUEDE ACCEDER");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogoSIC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTexto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(LogoSIC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTexto2)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel LabelTexto;
    private javax.swing.JLabel LabelTexto2;
    private javax.swing.JLabel LogoSIC;
    private javax.swing.JLabel TextLogo;
    // End of variables declaration//GEN-END:variables
}
