package Administrador;

import Utilidades.GestorInventario;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author gomez
 */
public class Inventario extends javax.swing.JPanel {
    
    DefaultTableModel mt = new DefaultTableModel();
    

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        String ids[] = {"Codigo del Producto", "Nombre del producto", "Valor", "Cantidad"};
        
        mt.setColumnIdentifiers(ids);
        jTable1.setModel(mt);
        
        Utilidades.GestorInventario.cargarInventarioDesdeArchivo();
        cargarProductosTabla();
        
    }
    private void registrarProductoDesdeAdmin(String codigo, String nombre, double valor, int cantidad) {
    GestorInventario.Producto nuevo = new GestorInventario.Producto(codigo, nombre, valor, cantidad);
    
    GestorInventario.agregarProducto(nuevo);
    }
    
    
    public void cargarProductosTabla() {
        mt.setRowCount(0); 
        for (Utilidades.GestorInventario.Producto producto : Utilidades.GestorInventario.obtenerTodosLosProductos()) {
            Object[] fila = {
                producto.codigo,
                producto.nombre,
                producto.valor,
                producto.cantidad
            };
            mt.addRow(fila);
        }
    }
    public void actualizarTabla() {
        cargarProductosTabla();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        AñadirJtable = new javax.swing.JPanel();
        AgregarLabel = new javax.swing.JLabel();
        EliminaJtable = new javax.swing.JPanel();
        QuitarLabel = new javax.swing.JLabel();
        EditarJtable = new javax.swing.JPanel();
        EditarTXT = new javax.swing.JLabel();
        CodigoTXT1 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        NombreTXT = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        ValorTXT = new javax.swing.JLabel();
        Valor = new javax.swing.JTextField();
        CantidadTXT = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        AñadirStock = new javax.swing.JLabel();
        TextLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(234, 234, 234));

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        AñadirJtable.setBackground(new java.awt.Color(76, 76, 76));
        AñadirJtable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AgregarLabel.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        AgregarLabel.setForeground(new java.awt.Color(255, 255, 255));
        AgregarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarLabel.setText("AGREGAR NUEVO PROD.");
        AgregarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AñadirJtableLayout = new javax.swing.GroupLayout(AñadirJtable);
        AñadirJtable.setLayout(AñadirJtableLayout);
        AñadirJtableLayout.setHorizontalGroup(
            AñadirJtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgregarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        AñadirJtableLayout.setVerticalGroup(
            AñadirJtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgregarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        EliminaJtable.setBackground(new java.awt.Color(76, 76, 76));
        EliminaJtable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        QuitarLabel.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        QuitarLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuitarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuitarLabel.setText("QUITAR PRODUCTO");
        QuitarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuitarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuitarLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EliminaJtableLayout = new javax.swing.GroupLayout(EliminaJtable);
        EliminaJtable.setLayout(EliminaJtableLayout);
        EliminaJtableLayout.setHorizontalGroup(
            EliminaJtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuitarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        EliminaJtableLayout.setVerticalGroup(
            EliminaJtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuitarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        EditarJtable.setBackground(new java.awt.Color(76, 76, 76));
        EditarJtable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        EditarTXT.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        EditarTXT.setForeground(new java.awt.Color(255, 255, 255));
        EditarTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditarTXT.setText("EDITAR PRODUCTO");
        EditarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EditarJtableLayout = new javax.swing.GroupLayout(EditarJtable);
        EditarJtable.setLayout(EditarJtableLayout);
        EditarJtableLayout.setHorizontalGroup(
            EditarJtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        EditarJtableLayout.setVerticalGroup(
            EditarJtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditarTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        CodigoTXT1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        CodigoTXT1.setForeground(new java.awt.Color(0, 0, 0));
        CodigoTXT1.setText("Codigo:");

        Codigo.setBackground(new java.awt.Color(255, 255, 255));
        Codigo.setForeground(new java.awt.Color(0, 0, 0));
        Codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });

        NombreTXT.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        NombreTXT.setForeground(new java.awt.Color(0, 0, 0));
        NombreTXT.setText("Nombre Producto:");

        Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ValorTXT.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        ValorTXT.setForeground(new java.awt.Color(0, 0, 0));
        ValorTXT.setText("Valor:");

        Valor.setBackground(new java.awt.Color(255, 255, 255));
        Valor.setForeground(new java.awt.Color(0, 0, 0));
        Valor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorActionPerformed(evt);
            }
        });

        CantidadTXT.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        CantidadTXT.setForeground(new java.awt.Color(0, 0, 0));
        CantidadTXT.setText("Cantidad:");

        Cantidad.setBackground(new java.awt.Color(255, 255, 255));
        Cantidad.setForeground(new java.awt.Color(0, 0, 0));
        Cantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AñadirStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/4574849.png"))); // NOI18N
        AñadirStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AñadirStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirStockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoTXT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Valor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AñadirStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AñadirJtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminaJtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditarJtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoTXT1)
                            .addComponent(NombreTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Codigo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ValorTXT)
                            .addComponent(CantidadTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre)
                            .addComponent(Cantidad)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminaJtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñadirJtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarJtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñadirStock))
                .addGap(12, 12, 12))
        );

        TextLogo.setFont(new java.awt.Font("Roboto", 1, 34)); // NOI18N
        TextLogo.setForeground(new java.awt.Color(51, 51, 51));
        TextLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TextLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/FavImage.png"))); // NOI18N
        TextLogo.setText("INVENTARIO");

        jTable1.setBackground(new java.awt.Color(234, 234, 234));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(TextLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(TextLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActionPerformed
    
   
    
    
    public void actualizarTablaInventario() {
    mt.setRowCount(0); 

    for (GestorInventario.Producto p : GestorInventario.obtenerTodosLosProductos()) {
        Object[] fila = {
            p.codigo,
            p.nombre,
            p.valor,
            p.cantidad
        };
        mt.addRow(fila);
        }
    }
    
    public static void verificarInventario(int codigo, int cantidades) {
        
    }
    
    private void AgregarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLabelMouseClicked
        if (Codigo.getText().equals("") || Nombre.getText().equals("") || Valor.getText().equals("") || Cantidad.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No ha ingresado algun dato, por favor verifique y vuelva a intentarlo");
        }
        else {
            String code = Codigo.getText();
            String name = Nombre.getText();
            double value = Double.valueOf(Valor.getText());
            int ammount = Integer.valueOf(Cantidad.getText());
            registrarProductoDesdeAdmin(code, name, value, ammount);
            mt.addRow(new Object[]{code, name, value, ammount});
            Codigo.setText("");
            Nombre.setText("");
            Valor.setText("");
            Cantidad.setText("");  
        }
        
    }//GEN-LAST:event_AgregarLabelMouseClicked

    private void QuitarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitarLabelMouseClicked
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            String codigoProducto = (String) jTable1.getValueAt(filaSeleccionada, 0);   
            mt.removeRow(filaSeleccionada);
            try {
                File archivo = new File("src/inventario.txt");
                List<String> lineas = Files.readAllLines(archivo.toPath());
                List<String> nuevasLineas = new ArrayList<>();

                for (String linea : lineas) {
                    if (!linea.startsWith(codigoProducto + ";")) {
                        nuevasLineas.add(linea);
                    }
                }

                Files.write(archivo.toPath(), nuevasLineas);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar el archivo: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para eliminar.");
        }
    }//GEN-LAST:event_QuitarLabelMouseClicked

    private void EditarTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarTXTMouseClicked
        if (Codigo.getText().equals("") || Nombre.getText().equals("") || Valor.getText().equals("") || Cantidad.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No ha ingresado algun dato, por favor verifique y vuelva a intentarlo");
        } else {
            int filaSeleccionada = jTable1.getSelectedRow();

            String codigoOriginal = (String) jTable1.getValueAt(filaSeleccionada, 0);

            mt.setValueAt(Codigo.getText(), filaSeleccionada, 0);
            mt.setValueAt(Nombre.getText(), filaSeleccionada, 1);
            mt.setValueAt(Double.valueOf(Valor.getText()), filaSeleccionada, 2);
            mt.setValueAt(Integer.valueOf(Cantidad.getText()), filaSeleccionada, 3);

            String nuevaLinea = Codigo.getText() + ";" + Nombre.getText() + ";" + Valor.getText() + ";" + Cantidad.getText();


            try {
                File archivo = new File("src/inventario.txt");
                List<String> lineas = Files.readAllLines(archivo.toPath());
                List<String> nuevasLineas = new ArrayList<>();

                for (String linea : lineas) {
                    if (linea.startsWith(codigoOriginal + ";")) {
                        nuevasLineas.add(nuevaLinea); 
                    } else {
                        nuevasLineas.add(linea);
                    }
                }

                Files.write(archivo.toPath(), nuevasLineas);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar el archivo: " + e.getMessage());
            }
            Codigo.setText("");
            Nombre.setText("");
            Valor.setText("");
            Cantidad.setText("");
        }
    }//GEN-LAST:event_EditarTXTMouseClicked

    private void AgregarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLabelMouseEntered
        AñadirJtable.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_AgregarLabelMouseEntered

    private void AgregarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLabelMouseExited
        AñadirJtable.setBackground(new Color(76, 76, 76));
    }//GEN-LAST:event_AgregarLabelMouseExited

    private void QuitarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitarLabelMouseEntered
        EliminaJtable.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_QuitarLabelMouseEntered

    private void QuitarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitarLabelMouseExited
        EliminaJtable.setBackground(new Color(76, 76, 76));
    }//GEN-LAST:event_QuitarLabelMouseExited

    private void EditarTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarTXTMouseEntered
        EditarJtable.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_EditarTXTMouseEntered

    private void EditarTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarTXTMouseExited
        EditarJtable.setBackground(new Color(76, 76, 76));
    }//GEN-LAST:event_EditarTXTMouseExited

    private void AñadirStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirStockMouseClicked
        // Aqui se debe añadir un popup que aparezca cuando el usuario de click al icono el cual le solicite que ingrese el codigo del producto para posteriormente solicitarle la cantidad de stock que desea añadir en otro popup
        String codigo = JOptionPane.showInputDialog(this, "Ingrese el código del producto:");
        if (codigo == null || codigo.trim().isEmpty()) {
            return; 
        }

        boolean productoEncontrado = false;

        try {
            File archivo = new File("src/inventario.txt");
            List<String> lineas = Files.readAllLines(archivo.toPath());
            List<String> nuevasLineas = new ArrayList<>();

            for (String linea : lineas) {
                if (linea.startsWith(codigo + ";")) {
                    productoEncontrado = true;

                    
                    String[] partes = linea.split(";");
                    if (partes.length < 4) continue;

                    String nombre = partes[1];
                    double valor = Double.parseDouble(partes[2]);
                    int cantidadActual = Integer.parseInt(partes[3]);

                    
                    String entradaCantidad = JOptionPane.showInputDialog(this, "Ingrese la cantidad de stock a añadir:");
                    if ((Integer.parseInt(entradaCantidad) < 1) || entradaCantidad == null || entradaCantidad.trim().isEmpty()) {
                        nuevasLineas.add(linea); // No se añadió nada, conservar línea original
                        continue;
                    }

                    int cantidadAgregar = Integer.parseInt(entradaCantidad);
                    int nuevaCantidad = cantidadActual + cantidadAgregar;

                    
                    String nuevaLinea = codigo + ";" + nombre + ";" + valor + ";" + nuevaCantidad;
                    nuevasLineas.add(nuevaLinea);

                    
                    for (int i = 0; i < jTable1.getRowCount(); i++) {
                        if (jTable1.getValueAt(i, 0).equals(codigo)) {
                            jTable1.setValueAt(nuevaCantidad, i, 3);
                            break;
                        }
                    }
                } else {
                    nuevasLineas.add(linea); 
                }
            }

            if (!productoEncontrado) {
                JOptionPane.showMessageDialog(this, "Producto no encontrado con el código ingresado.");
            } else {
                Files.write(archivo.toPath(), nuevasLineas); // Guardar archivo actualizado
            }
        } catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el stock: " + e.getMessage());
        }
    
    }//GEN-LAST:event_AñadirStockMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarLabel;
    private javax.swing.JPanel AñadirJtable;
    private javax.swing.JLabel AñadirStock;
    private javax.swing.JPanel Background;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JLabel CantidadTXT;
    private javax.swing.JTextField Codigo;
    private javax.swing.JLabel CodigoTXT1;
    private javax.swing.JPanel EditarJtable;
    private javax.swing.JLabel EditarTXT;
    private javax.swing.JPanel EliminaJtable;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NombreTXT;
    private javax.swing.JLabel QuitarLabel;
    private javax.swing.JLabel TextLogo;
    private javax.swing.JTextField Valor;
    private javax.swing.JLabel ValorTXT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
