package Login;

import Administrador.Administrador;
import Cajero.Cajero;
import java.awt.Color;
import javax.swing.ImageIcon;


public class LoginJFRAME extends javax.swing.JFrame {
    
    
    Administrador administrador;
    Cajero cajero;
    
    
    
    
    int xMouse, yMouse;
    Color fondo = new Color(243, 243, 243);
    Color salida = new Color(206, 70, 41);
    
    
    
    
    /**
     * Creates new form LoginJFRAME
     */
    public LoginJFRAME() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/LogoSinFondo.png")).getImage());
        
        Usuario.inicializarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Login_Image = new javax.swing.JLabel();
        TextLogo = new javax.swing.JLabel();
        Logo_Image = new javax.swing.JLabel();
        City_Background = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        ExitBTN = new javax.swing.JPanel();
        ExitLabel = new javax.swing.JLabel();
        Iniciar_sesion = new javax.swing.JLabel();
        UsuarioLabel = new javax.swing.JLabel();
        SeparadorUsuario = new javax.swing.JSeparator();
        UsuarioTextField = new javax.swing.JTextField();
        SeparadorContraseña = new javax.swing.JSeparator();
        ContraseñaLabel = new javax.swing.JLabel();
        EntrarBTN = new javax.swing.JPanel();
        TextoEntrar = new javax.swing.JLabel();
        ContraseñaField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        Background.setBackground(new java.awt.Color(234, 234, 234));
        Background.setMinimumSize(new java.awt.Dimension(800, 500));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Image.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        Login_Image.setForeground(new java.awt.Color(6, 32, 42));
        Login_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/FavImage.png"))); // NOI18N
        Login_Image.setText("S I C");
        Login_Image.setAlignmentX(0.5F);
        Background.add(Login_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 120, 60));

        TextLogo.setFont(new java.awt.Font("Roboto", 1, 34)); // NOI18N
        TextLogo.setForeground(new java.awt.Color(255, 255, 255));
        TextLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextLogo.setText("S I C");
        Background.add(TextLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, -1));

        Logo_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/Logo.png"))); // NOI18N
        Background.add(Logo_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 190));

        City_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/CITY EDITADA.png"))); // NOI18N
        City_Background.setText("jLabel1");
        Background.add(City_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 320, 500));

        Header.setBackground(new java.awt.Color(234, 234, 234));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        ExitBTN.setBackground(new java.awt.Color(232, 232, 232));
        ExitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBTNMouseExited(evt);
            }
        });

        ExitLabel.setBackground(new java.awt.Color(232, 232, 232));
        ExitLabel.setFont(new java.awt.Font("Roboto Light", 0, 32)); // NOI18N
        ExitLabel.setForeground(new java.awt.Color(0, 0, 0));
        ExitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitLabel.setText("X");
        ExitLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout ExitBTNLayout = new javax.swing.GroupLayout(ExitBTN);
        ExitBTN.setLayout(ExitBTNLayout);
        ExitBTNLayout.setHorizontalGroup(
            ExitBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ExitBTNLayout.setVerticalGroup(
            ExitBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 760, Short.MAX_VALUE)
                .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        Iniciar_sesion.setFont(new java.awt.Font("Roboto Black", 1, 30)); // NOI18N
        Iniciar_sesion.setForeground(new java.awt.Color(6, 32, 42));
        Iniciar_sesion.setText("INICIAR SESION");
        Background.add(Iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 240, -1));

        UsuarioLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        UsuarioLabel.setForeground(new java.awt.Color(6, 32, 42));
        UsuarioLabel.setText("Usuario");
        Background.add(UsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        SeparadorUsuario.setBackground(new java.awt.Color(0, 0, 0));
        SeparadorUsuario.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(SeparadorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 360, 10));

        UsuarioTextField.setBackground(new java.awt.Color(234, 234, 234));
        UsuarioTextField.setForeground(new java.awt.Color(165, 165, 165));
        UsuarioTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        UsuarioTextField.setText("Ingrese su Codigo de Usuario");
        UsuarioTextField.setBorder(null);
        UsuarioTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsuarioTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsuarioTextFieldFocusLost(evt);
            }
        });
        UsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextFieldActionPerformed(evt);
            }
        });
        Background.add(UsuarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 360, 50));

        SeparadorContraseña.setBackground(new java.awt.Color(0, 0, 0));
        SeparadorContraseña.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(SeparadorContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 360, 10));

        ContraseñaLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        ContraseñaLabel.setForeground(new java.awt.Color(6, 32, 42));
        ContraseñaLabel.setText("Contraseña");
        Background.add(ContraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        EntrarBTN.setBackground(new java.awt.Color(76, 76, 76));
        EntrarBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EntrarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrarBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrarBTNMouseExited(evt);
            }
        });

        TextoEntrar.setBackground(new java.awt.Color(0, 0, 0));
        TextoEntrar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        TextoEntrar.setForeground(new java.awt.Color(234, 234, 234));
        TextoEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoEntrar.setText("ENTRAR");
        TextoEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoEntrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TextoEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EntrarBTNLayout = new javax.swing.GroupLayout(EntrarBTN);
        EntrarBTN.setLayout(EntrarBTNLayout);
        EntrarBTNLayout.setHorizontalGroup(
            EntrarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        EntrarBTNLayout.setVerticalGroup(
            EntrarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Background.add(EntrarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 180, 40));

        ContraseñaField.setBackground(new java.awt.Color(232, 232, 232));
        ContraseñaField.setForeground(new java.awt.Color(178, 178, 178));
        ContraseñaField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ContraseñaField.setText("******");
        ContraseñaField.setBorder(null);
        ContraseñaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContraseñaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContraseñaFieldFocusLost(evt);
            }
        });
        Background.add(ContraseñaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 360, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextFieldActionPerformed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void ExitBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBTNMouseClicked

    private void ExitBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseEntered
        ExitBTN.setBackground(salida);
        ExitLabel.setForeground(Color.white);
    }//GEN-LAST:event_ExitBTNMouseEntered

    private void ExitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseExited
        ExitBTN.setBackground(fondo);
        ExitLabel.setForeground(Color.black);
    }//GEN-LAST:event_ExitBTNMouseExited

    private void TextoEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoEntrarMouseEntered
        EntrarBTN.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_TextoEntrarMouseEntered

    private void EntrarBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarBTNMouseEntered
        //AQUI NO HAY NADA
    }//GEN-LAST:event_EntrarBTNMouseEntered

    private void EntrarBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarBTNMouseExited
        //AQUI NO HAY NADA
    }//GEN-LAST:event_EntrarBTNMouseExited

    private void TextoEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoEntrarMouseExited
        EntrarBTN.setBackground(new Color(76, 76, 76));
    }//GEN-LAST:event_TextoEntrarMouseExited

    private void UsuarioTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuarioTextFieldFocusGained
        if (UsuarioTextField.getText().equals("Ingrese su Codigo de Usuario")){
            UsuarioTextField.setText("");
            UsuarioTextField.setForeground(Color.black);
        }
        
        
    }//GEN-LAST:event_UsuarioTextFieldFocusGained

    private void UsuarioTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuarioTextFieldFocusLost
           if(UsuarioTextField.getText().isEmpty()) {
            UsuarioTextField.setText("Ingrese su Codigo de Usuario");
            UsuarioTextField.setForeground(new Color(165, 165, 165));
        } 
    }//GEN-LAST:event_UsuarioTextFieldFocusLost

    private void ContraseñaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñaFieldFocusGained
        if(String.valueOf(ContraseñaField.getPassword()).equals("******")) {
            ContraseñaField.setText("");
            ContraseñaField.setForeground(Color.black);
        }
        
        
    }//GEN-LAST:event_ContraseñaFieldFocusGained

    private void ContraseñaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñaFieldFocusLost
        if (String.valueOf(ContraseñaField.getPassword()).isEmpty()){
            ContraseñaField.setText("******");
            ContraseñaField.setForeground(new Color (165, 165, 165));
        }
    }//GEN-LAST:event_ContraseñaFieldFocusLost

    private void TextoEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoEntrarMouseClicked
        String usuarioIngresado = UsuarioTextField.getText();
        String contraseñaIngresada = String.valueOf(ContraseñaField.getPassword());

        if (Usuario.validarUsuario(usuarioIngresado, contraseñaIngresada)) {
            if (Usuario.tipoUsuario(usuarioIngresado, contraseñaIngresada)) {
                
                administrador = new Administrador(this);
                administrador.setVisible(true);
                ContraseñaField.setText("");
                UsuarioTextField.setText("");
                this.setVisible(false); 
            }
            else {
                
                cajero = new Cajero(this);
                cajero.setVisible(true);
                ContraseñaField.setText("");
                UsuarioTextField.setText("");
                this.setVisible(false);
            }
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "El inicio de sesión ha sido incorrecto, vuelva a intentarlo.");
        }
        
        
        /*if(UsuarioTextField.getText().equals("Ingrese su Codigo de Usuario") || UsuarioTextField.getText().isEmpty()
        || String.valueOf(ContraseñaField.getPassword()).equals("******") || String.valueOf(ContraseñaField.getPassword()).isEmpty() ||
       !UsuarioTextField.getText().equals(admin1.getUsername()) || !String.valueOf(ContraseñaField.getPassword()).equals(admin1.getPassword())) {
            javax.swing.JOptionPane.showMessageDialog(this, "El inicio de sesion ha sido incorrecto, vuelva a intentarlo");
        }*/
        
    }//GEN-LAST:event_TextoEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFRAME().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel City_Background;
    private javax.swing.JPasswordField ContraseñaField;
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JPanel EntrarBTN;
    private javax.swing.JPanel ExitBTN;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Iniciar_sesion;
    private javax.swing.JLabel Login_Image;
    private javax.swing.JLabel Logo_Image;
    private javax.swing.JSeparator SeparadorContraseña;
    private javax.swing.JSeparator SeparadorUsuario;
    private javax.swing.JLabel TextLogo;
    private javax.swing.JLabel TextoEntrar;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JTextField UsuarioTextField;
    // End of variables declaration//GEN-END:variables
}
