package Cajero;

import Administrador.Home;
import Administrador.Inventario;
import java.awt.BorderLayout;
import java.awt.Color;
import Login.LoginJFRAME;
import javax.swing.ImageIcon;

/**
 *
 * @author gomez
 */
public class Cajero extends javax.swing.JFrame {
    
    
    private LoginJFRAME loginFrame;
    int xMouse, yMouse;
    Color fondo = new Color(243, 243, 243);
    Color salida = new Color(206, 70, 41);
    /**
     * Creates new form Cajero
     */
    public Cajero() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/LogoSinFondo.png")).getImage());
        Home home1 = new Home();
        
        home1.setSize(730, 500);
        home1.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(home1, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }
    public Cajero(LoginJFRAME loginFrame) {
    this.loginFrame = loginFrame;
    initComponents();
    setIconImage(new ImageIcon(getClass().getResource("/LogoSinFondo.png")).getImage());
    Home home1 = new Home();
        
    home1.setSize(730, 500);
    home1.setLocation(0, 0);

    Content.removeAll();
    Content.add(home1, BorderLayout.CENTER);
    Content.revalidate();
    Content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        AdminLogo = new javax.swing.JLabel();
        RegistrarVenta = new javax.swing.JPanel();
        RegistrarVentaTXT = new javax.swing.JLabel();
        CityBckg = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        ExitBTN = new javax.swing.JPanel();
        ExitLabel = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(234, 234, 234));
        Background.setMinimumSize(new java.awt.Dimension(1000, 500));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/CajeroImagen.png"))); // NOI18N
        AdminLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLogoMouseClicked(evt);
            }
        });
        Background.add(AdminLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 230));

        RegistrarVenta.setBackground(new java.awt.Color(76, 76, 76));
        RegistrarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        RegistrarVentaTXT.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        RegistrarVentaTXT.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarVentaTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrarVentaTXT.setText("REGISTRAR VENTA");
        RegistrarVentaTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarVentaTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarVentaTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarVentaTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RegistrarVentaLayout = new javax.swing.GroupLayout(RegistrarVenta);
        RegistrarVenta.setLayout(RegistrarVentaLayout);
        RegistrarVentaLayout.setHorizontalGroup(
            RegistrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrarVentaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        RegistrarVentaLayout.setVerticalGroup(
            RegistrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrarVentaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Background.add(RegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 60));

        CityBckg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/CITY EDITADA.png"))); // NOI18N
        Background.add(CityBckg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 330, -1));

        Header.setBackground(new java.awt.Color(234, 234, 234));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        ExitBTN.setBackground(new java.awt.Color(232, 232, 232));
        ExitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBTNMouseExited(evt);
            }
        });

        ExitLabel.setBackground(new java.awt.Color(232, 232, 232));
        ExitLabel.setFont(new java.awt.Font("Roboto Light", 0, 32)); // NOI18N
        ExitLabel.setForeground(new java.awt.Color(0, 0, 0));
        ExitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitLabel.setText("X");
        ExitLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout ExitBTNLayout = new javax.swing.GroupLayout(ExitBTN);
        ExitBTN.setLayout(ExitBTNLayout);
        ExitBTNLayout.setHorizontalGroup(
            ExitBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ExitBTNLayout.setVerticalGroup(
            ExitBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 960, Short.MAX_VALUE)
                .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        Content.setBackground(new java.awt.Color(234, 234, 234));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        Background.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 730, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBTNMouseClicked

    private void ExitBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseEntered
        ExitBTN.setBackground(salida);
        ExitLabel.setForeground(Color.white);
    }//GEN-LAST:event_ExitBTNMouseEntered

    private void ExitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseExited
        ExitBTN.setBackground(fondo);
        ExitLabel.setForeground(Color.black);
    }//GEN-LAST:event_ExitBTNMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void AdminLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLogoMouseClicked
        loginFrame.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_AdminLogoMouseClicked

    private void RegistrarVentaTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarVentaTXTMouseClicked
        Inventario panelAdmin = new Inventario();
        Inventario1 inventario1 = new Inventario1(panelAdmin);

        inventario1.setSize(730, 500);
        inventario1.setLocation(0, 0);

        Content.removeAll();
        Content.add(inventario1, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_RegistrarVentaTXTMouseClicked

    private void RegistrarVentaTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarVentaTXTMouseEntered
        RegistrarVenta.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_RegistrarVentaTXTMouseEntered

    private void RegistrarVentaTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarVentaTXTMouseExited
        RegistrarVenta.setBackground(new Color(76, 76, 76));
    }//GEN-LAST:event_RegistrarVentaTXTMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLogo;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel CityBckg;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel ExitBTN;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel RegistrarVenta;
    private javax.swing.JLabel RegistrarVentaTXT;
    // End of variables declaration//GEN-END:variables
}
