package Cajero;

import javax.swing.table.DefaultTableModel;
import Administrador.Inventario;
import Utilidades.GestorInventario;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author gomez
 */
public class Inventario1 extends javax.swing.JPanel {

    
    
    DefaultTableModel mt1 = new DefaultTableModel();
    private Inventario panelAdmin;
    /**
     * Creates new form Inventario1
     */
    public Inventario1() {
        initComponents();
        String ids[] = {"Codigo del Producto", "Nombre del producto", "Precio", "Cantidad", "Total"};
        
        mt1.setColumnIdentifiers(ids);
        jTable1.setModel(mt1);
        this.panelAdmin = panelAdmin;
    }
    
    public Inventario1(Inventario panelAdmin) {
    initComponents();
    String ids[] = {"Codigo del Producto", "Nombre del producto", "Precio", "Cantidad", "Total"};
    mt1.setColumnIdentifiers(ids);
    jTable1.setModel(mt1);
    this.panelAdmin = panelAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bckgr = new javax.swing.JPanel();
        TextLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        AñadirJtable = new javax.swing.JPanel();
        AgregarLabel = new javax.swing.JLabel();
        FacturaBTN = new javax.swing.JPanel();
        GenerarFacturaTXT = new javax.swing.JLabel();

        bckgr.setBackground(new java.awt.Color(234, 234, 234));
        bckgr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextLogo.setFont(new java.awt.Font("Roboto", 1, 34)); // NOI18N
        TextLogo.setForeground(new java.awt.Color(51, 51, 51));
        TextLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/FavImage.png"))); // NOI18N
        TextLogo.setText("Venta");
        bckgr.add(TextLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 730, -1));

        jTable1.setBackground(new java.awt.Color(234, 234, 234));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bckgr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 700, 310));

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        AñadirJtable.setBackground(new java.awt.Color(76, 76, 76));
        AñadirJtable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AgregarLabel.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        AgregarLabel.setForeground(new java.awt.Color(255, 255, 255));
        AgregarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarLabel.setText("AGREGAR PRODUCTO");
        AgregarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AñadirJtableLayout = new javax.swing.GroupLayout(AñadirJtable);
        AñadirJtable.setLayout(AñadirJtableLayout);
        AñadirJtableLayout.setHorizontalGroup(
            AñadirJtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgregarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        AñadirJtableLayout.setVerticalGroup(
            AñadirJtableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgregarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        FacturaBTN.setBackground(new java.awt.Color(76, 76, 76));

        GenerarFacturaTXT.setBackground(new java.awt.Color(76, 76, 76));
        GenerarFacturaTXT.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        GenerarFacturaTXT.setForeground(new java.awt.Color(255, 255, 255));
        GenerarFacturaTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenerarFacturaTXT.setText("GENERAR FACTURA");
        GenerarFacturaTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GenerarFacturaTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenerarFacturaTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GenerarFacturaTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GenerarFacturaTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FacturaBTNLayout = new javax.swing.GroupLayout(FacturaBTN);
        FacturaBTN.setLayout(FacturaBTNLayout);
        FacturaBTNLayout.setHorizontalGroup(
            FacturaBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GenerarFacturaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        FacturaBTNLayout.setVerticalGroup(
            FacturaBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GenerarFacturaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(AñadirJtable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(FacturaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AñadirJtable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FacturaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        bckgr.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 730, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckgr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckgr, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void agregarProductoATabla(String codigo, int cantidad) {
    GestorInventario.Producto producto = GestorInventario.buscarProducto(codigo);

    if (producto == null) {
        JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (producto.cantidad < cantidad) {
        JOptionPane.showMessageDialog(this, "Stock insuficiente.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    double total = producto.valor * cantidad;

    Object[] fila = {
        producto.codigo,
        producto.nombre,
        producto.valor,
        cantidad,
        total
    };

    mt1.addRow(fila);
    }
    
    
    private void agregarProductoAFactura(String codigoIngresado, int cantidadIngresada) {
    GestorInventario.Producto producto = GestorInventario.buscarProducto(codigoIngresado);

    if (producto == null) {
        JOptionPane.showMessageDialog(this, "El producto no pudo ser encontrado en el inventario", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (cantidadIngresada > producto.cantidad) {
        JOptionPane.showMessageDialog(this, "La cantidad solicitada es mayor a la cantidad actual de stock", "Stock insuficiente", JOptionPane.WARNING_MESSAGE);
        return;
    }

    double total = producto.valor * cantidadIngresada;

    Object[] fila = {
        producto.codigo,
        producto.nombre,
        producto.valor,
        cantidadIngresada,
        total
    };

    mt1.addRow(fila);

    
    //GestorInventario.descontarStock(producto.codigo, cantidadIngresada);
    }
    
    
    private void AgregarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLabelMouseClicked

        String codigo = JOptionPane.showInputDialog("Ingrese el código del producto:");
        String cantidadStr = JOptionPane.showInputDialog("Ingrese la cantidad a agregar:");

        try {
            int cantidad = Integer.parseInt(cantidadStr);
            agregarProductoAFactura(codigo, cantidad);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La cantidad debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AgregarLabelMouseClicked

    private void GenerarFacturaTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarFacturaTXTMouseClicked
        double totalFactura = 0;
        for (int i = 0; i < mt1.getRowCount(); i++) {
            String codigo = mt1.getValueAt(i, 0).toString();
            int cantidad = Integer.parseInt(mt1.getValueAt(i, 3).toString());

            if (!Utilidades.GestorInventario.descontarStock(codigo, cantidad)) {
                JOptionPane.showMessageDialog(this, "Error al descontar inventario para el producto: " + codigo);
                return;
            }

            totalFactura += Double.parseDouble(mt1.getValueAt(i, 4).toString());
        }

        if (panelAdmin != null) {
            panelAdmin.actualizarTablaInventario();
        }

        mt1.setRowCount(0); 
        JOptionPane.showMessageDialog(this, "Total a pagar por el cliente: $" + totalFactura);
    }//GEN-LAST:event_GenerarFacturaTXTMouseClicked

    private void AgregarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLabelMouseEntered
        AñadirJtable.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_AgregarLabelMouseEntered

    private void AgregarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLabelMouseExited
        AñadirJtable.setBackground(new Color(76, 76, 76));
    }//GEN-LAST:event_AgregarLabelMouseExited

    private void GenerarFacturaTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarFacturaTXTMouseEntered
        FacturaBTN.setBackground(new Color(30, 30, 30));
    }//GEN-LAST:event_GenerarFacturaTXTMouseEntered

    private void GenerarFacturaTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarFacturaTXTMouseExited
        FacturaBTN.setBackground(new Color(76, 76, 76));
    }//GEN-LAST:event_GenerarFacturaTXTMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarLabel;
    private javax.swing.JPanel AñadirJtable;
    private javax.swing.JPanel FacturaBTN;
    private javax.swing.JLabel GenerarFacturaTXT;
    private javax.swing.JLabel TextLogo;
    private javax.swing.JPanel bckgr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
